import { createClient } from "@supabase/supabase-js";
import { Product } from "./types";

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || "https://placeholder.supabase.co";
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || "placeholder-key";

export const supabase = createClient(supabaseUrl, supabaseAnonKey);

export const INITIAL_MOCK_PRODUCTS: Product[] = [
  {
    id: "p1",
    barcode: "8991001001",
    name: "Pupuk Urea Subur 50kg",
    category: "Pupuk",
    buy_price: 120000,
    sell_price: 145000,
    stock: 25,
    min_stock: 5,
    created_at: new Date().toISOString(),
  },
  {
    id: "p2",
    barcode: "8991001002",
    name: "Pupuk NPK Mutiara 16-16-16 1kg",
    category: "Pupuk",
    buy_price: 18000,
    sell_price: 23000,
    stock: 40,
    min_stock: 10,
    created_at: new Date().toISOString(),
  },
  {
    id: "p3",
    barcode: "8991001003",
    name: "Benih Padi Ciherang Unggul 5kg",
    category: "Benih",
    buy_price: 65000,
    sell_price: 80000,
    stock: 15,
    min_stock: 5,
    created_at: new Date().toISOString(),
  },
  {
    id: "p4",
    barcode: "8991001004",
    name: "Benih Jagung Hibrida BISI-18 1kg",
    category: "Benih",
    buy_price: 85000,
    sell_price: 105000,
    stock: 8,
    min_stock: 3,
    created_at: new Date().toISOString(),
  },
  {
    id: "p5",
    barcode: "8991001005",
    name: "Pestisida RoundUp 1 Liter",
    category: "Pestisida",
    buy_price: 75000,
    sell_price: 92000,
    stock: 12,
    min_stock: 4,
    created_at: new Date().toISOString(),
  },
  {
    id: "p6",
    barcode: "8991001006",
    name: "Fungisida Antracol 70WP 500g",
    category: "Pestisida",
    buy_price: 48000,
    sell_price: 60000,
    stock: 3,
    min_stock: 5,
    created_at: new Date().toISOString(),
  },
  {
    id: "p7",
    barcode: "8991001007",
    name: "Cangkul Baja Asli Tani",
    category: "Alat Tani",
    buy_price: 55000,
    sell_price: 75000,
    stock: 6,
    min_stock: 2,
    created_at: new Date().toISOString(),
  },
  {
    id: "p8",
    barcode: "8991001008",
    name: "Sprayer Elektrik Hama 16 Liter",
    category: "Alat Tani",
    buy_price: 280000,
    sell_price: 350000,
    stock: 2,
    min_stock: 3,
    created_at: new Date().toISOString(),
  },
  {
    id: "p9",
    barcode: "8991001009",
    name: "Benih Cabai Rawit Setan 10g",
    category: "Benih",
    buy_price: 22000,
    sell_price: 30000,
    stock: 0,
    min_stock: 5,
    created_at: new Date().toISOString(),
  },
];
